package:
  name: pywindow
  version: "0.0.1"

source:
  git_rev: v0.0.1
  git_url: https://github.com/marcinmiklitz/pywindow.git

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - scikit-learn

test:
  imports:
    - pywindow

about:
  home: https://github.com/marcinmiklitz/pywindow
  license: MIT
  license_file: LICENSE
